### ISSUE TITLE
✨ 유저 도메인 개발

### ISSUE THREAD

**Issue by ye0ngeun** [DAEJJA/daejja-backend#1]
## 📌 Description
- 유저 관련 도메인을 개발합니다

## 📝 To-do
- [x] 유저 도메인 구현
- [x] 토큰 페어 도메인 구현
- [x] 데이터베이스 연결 확인
